/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.ventanas;

import com.mycompany.integrador.Integrador;
import com.mycompany.integrador.Materia;
import static com.mycompany.ventanas.LogicaComun.llamarModal;
import java.awt.Graphics;
import java.awt.Image;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.JSpinner;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ezequ
 */
public final class Ventana extends javax.swing.JFrame {
    FondoPanel fondo = new FondoPanel();
    /**
     * Creates new form Ventana
     */
    public Ventana() {
        this.setContentPane(fondo);
        initComponents();
        this.setLocationRelativeTo(null);
        cerrarSesion.setVisible(false);
        panelAltaMateria.setVisible(false);
        panelAltaAlumno.setVisible(false);
        panelVerMaterias.setVisible(false);
        panelVerAlumnos.setVisible(false);
        profesor.setVisible(false);
        alumno.setVisible(false);
        panelInscripcion.setVisible(false);
        panelInscripcion.setVisible(false);
        this.cleanError();
    }

    public JPanel getLogin() {
        return login;
    }

    public JButton getMakeLogin() {
        return makeLogin;
    }

    public JPasswordField getPassword() {
        return password;
    }

    public JPanel getProfesor() {
        return profesor;
    }

    public JPanel getAlumno() {
        return alumno;
    }

    public JTextField getUser() {
        return user;
    }

    public JPanel getPanelAltaAlumno() {
        return panelAltaAlumno;
    }

    public JPanel getPanelAltaMateria() {
        return panelAltaMateria;
    }

    public JPanel getPanelVerAlumnos() {
        return panelVerAlumnos;
    }

    public JPanel getPanelVerMaterias() {
        return panelVerMaterias;
    }

    public JButton getCerrarSesion() {
        return cerrarSesion;
    }

    public JComboBox<String> getListaCorrelativas1() {
        return listaCorrelativas1;
    }

    public JComboBox<String> getListaCorrelativas2() {
        return listaCorrelativas2;
    }

    public JComboBox<String> getListaCorrelativas3() {
        return listaCorrelativas3;
    }

    public JComboBox<String> getListaCorrelativas4() {
        return listaCorrelativas4;
    }

    public JComboBox<String> getListaCorrelativas5() {
        return listaCorrelativas5;
    }

    public JComboBox<String> getListaMaterias() {
        return listaMaterias;
    }

    public JTextField getNombreMateria() {
        return nombreMateria;
    }

    public JTable getTablaAlumnos() {
        return tablaAlumnos;
    }

    public JTable getTablaMaterias() {
        return tablaMaterias;
    }

    public JTextField getCargarNombreAlumno() {
        return CargarNombreAlumno;
    }

    public JTable getTablaMateriasAprobadas() {
        return tablaMateriasAprobadas;
    }

    public JTextField getNombreMateriaAConsultar() {
        return nombreMateriaAConsultar;
    }

    public JSpinner getLegajoAlumnoAConsultar() {
        return legajoAlumnoAConsultar;
    }

    public JSpinner getLegajoAlumnoAInscribir() {
        return legajoAlumnoAInscribir;
    }

    public JTable getTablaInscripcion() {
        return tablaInscripcion;
    }

    public JPanel getPrincipal() {
        return principal;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        principal = new javax.swing.JPanel();
        close = new javax.swing.JButton();
        cerrarSesion = new javax.swing.JButton();
        alumno = new javax.swing.JPanel();
        inscripcion = new javax.swing.JButton();
        panelInscripcion = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaInscripcion = new javax.swing.JTable();
        legajoAlumnoAInscribir = new javax.swing.JSpinner();
        jLabel15 = new javax.swing.JLabel();
        ConsultarMateriasParaInscripcion = new javax.swing.JButton();
        Inscribir1 = new javax.swing.JButton();
        profesor = new javax.swing.JPanel();
        altaMateria = new javax.swing.JButton();
        altaAlumno = new javax.swing.JButton();
        verMaterias = new javax.swing.JButton();
        verAlumnos = new javax.swing.JButton();
        panelAltaMateria = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        listaMaterias = new javax.swing.JComboBox<>();
        nombreMateria = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        listaCorrelativas1 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        listaCorrelativas2 = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        listaCorrelativas3 = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        listaCorrelativas4 = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        listaCorrelativas5 = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        saveMateria = new javax.swing.JButton();
        limpiarCampos = new javax.swing.JButton();
        nuevaMateria = new javax.swing.JButton();
        volverLista = new javax.swing.JButton();
        panelAltaAlumno = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        saveAlumno = new javax.swing.JButton();
        limpiarCampos1 = new javax.swing.JButton();
        CargarNombreAlumno = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        tablaMateriasAprobadas = new javax.swing.JTable();
        panelVerMaterias = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        nombreMateriaAConsultar = new javax.swing.JTextField();
        ConsultarTodasLasMaterias = new javax.swing.JButton();
        consultarMateriaPuntual = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaMaterias = new javax.swing.JTable();
        panelVerAlumnos = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaAlumnos = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        consultarAlumnoPuntual = new javax.swing.JButton();
        ConsultarTodosLosAlumnos = new javax.swing.JButton();
        legajoAlumnoAConsultar = new javax.swing.JSpinner();
        login = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        user = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        makeLogin = new javax.swing.JButton();
        error1 = new javax.swing.JLabel();
        error2 = new javax.swing.JLabel();
        error3 = new javax.swing.JLabel();
        error4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(600, 800));
        setMinimumSize(new java.awt.Dimension(600, 800));
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(600, 800));

        principal.setBackground(new java.awt.Color(51, 255, 51));
        principal.setAlignmentX(0.0F);
        principal.setAlignmentY(0.0F);
        principal.setMaximumSize(new java.awt.Dimension(600, 800));
        principal.setMinimumSize(new java.awt.Dimension(600, 800));
        principal.setOpaque(false);
        principal.setPreferredSize(new java.awt.Dimension(600, 800));
        principal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        close.setBackground(new java.awt.Color(255, 0, 0));
        close.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        close.setText("X");
        close.setAlignmentY(0.0F);
        close.setBorder(null);
        close.setBorderPainted(false);
        close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        close.setFocusPainted(false);
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });
        principal.add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 0, 40, 40));

        cerrarSesion.setBackground(new java.awt.Color(0, 153, 255));
        cerrarSesion.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        cerrarSesion.setText("Logout");
        cerrarSesion.setAlignmentY(0.0F);
        cerrarSesion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cerrarSesion.setBorderPainted(false);
        cerrarSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cerrarSesion.setFocusPainted(false);
        cerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarSesionActionPerformed(evt);
            }
        });
        principal.add(cerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 40));

        alumno.setBackground(new java.awt.Color(51, 204, 255));

        inscripcion.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        inscripcion.setText("Inscripcion");
        inscripcion.setMaximumSize(new java.awt.Dimension(150, 30));
        inscripcion.setMinimumSize(new java.awt.Dimension(150, 30));
        inscripcion.setPreferredSize(new java.awt.Dimension(150, 30));
        inscripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inscripcionActionPerformed(evt);
            }
        });

        panelInscripcion.setEnabled(false);
        panelInscripcion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panelInscripcion.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane3.setMaximumSize(new java.awt.Dimension(580, 402));
        jScrollPane3.setMinimumSize(new java.awt.Dimension(580, 402));
        jScrollPane3.setPreferredSize(new java.awt.Dimension(580, 402));

        tablaInscripcion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Materia", "Inscribir"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaInscripcion.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tablaInscripcion.setShowHorizontalLines(true);
        tablaInscripcion.setShowVerticalLines(true);
        jScrollPane3.setViewportView(tablaInscripcion);

        panelInscripcion.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 580, 260));

        legajoAlumnoAInscribir.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        legajoAlumnoAInscribir.setMaximumSize(new java.awt.Dimension(170, 28));
        legajoAlumnoAInscribir.setMinimumSize(new java.awt.Dimension(170, 28));
        legajoAlumnoAInscribir.setPreferredSize(new java.awt.Dimension(170, 28));
        panelInscripcion.add(legajoAlumnoAInscribir, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, -1, -1));

        jLabel15.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel15.setText("Legajo del Alumno:");
        jLabel15.setPreferredSize(new java.awt.Dimension(166, 28));
        panelInscripcion.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 150, -1));

        ConsultarMateriasParaInscripcion.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        ConsultarMateriasParaInscripcion.setText("Consultar Materias");
        ConsultarMateriasParaInscripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultarMateriasParaInscripcionActionPerformed(evt);
            }
        });
        panelInscripcion.add(ConsultarMateriasParaInscripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 30, 190, -1));

        Inscribir1.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        Inscribir1.setText("Realizar Inscripcion");
        Inscribir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Inscribir1ActionPerformed(evt);
            }
        });
        panelInscripcion.add(Inscribir1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 380, 190, -1));

        javax.swing.GroupLayout alumnoLayout = new javax.swing.GroupLayout(alumno);
        alumno.setLayout(alumnoLayout);
        alumnoLayout.setHorizontalGroup(
            alumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, alumnoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(panelInscripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, alumnoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(inscripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(225, 225, 225))
        );
        alumnoLayout.setVerticalGroup(
            alumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(alumnoLayout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(inscripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addComponent(panelInscripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        principal.add(alumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 800));

        profesor.setBackground(new java.awt.Color(51, 204, 255));
        profesor.setAlignmentX(0.0F);
        profesor.setAlignmentY(0.0F);
        profesor.setMaximumSize(new java.awt.Dimension(600, 800));
        profesor.setMinimumSize(new java.awt.Dimension(600, 800));
        profesor.setPreferredSize(new java.awt.Dimension(600, 800));
        profesor.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        altaMateria.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        altaMateria.setText("Crear materia");
        altaMateria.setMaximumSize(new java.awt.Dimension(150, 30));
        altaMateria.setMinimumSize(new java.awt.Dimension(150, 30));
        altaMateria.setPreferredSize(new java.awt.Dimension(150, 30));
        altaMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                altaMateriaActionPerformed(evt);
            }
        });
        profesor.add(altaMateria, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, -1, -1));

        altaAlumno.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        altaAlumno.setText("Alta de alumno");
        altaAlumno.setMaximumSize(new java.awt.Dimension(150, 30));
        altaAlumno.setMinimumSize(new java.awt.Dimension(150, 30));
        altaAlumno.setPreferredSize(new java.awt.Dimension(150, 30));
        altaAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                altaAlumnoActionPerformed(evt);
            }
        });
        profesor.add(altaAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 60, -1, -1));

        verMaterias.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        verMaterias.setText("Ver materias");
        verMaterias.setMaximumSize(new java.awt.Dimension(150, 30));
        verMaterias.setMinimumSize(new java.awt.Dimension(150, 30));
        verMaterias.setPreferredSize(new java.awt.Dimension(150, 30));
        verMaterias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verMateriasActionPerformed(evt);
            }
        });
        profesor.add(verMaterias, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, -1, -1));

        verAlumnos.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        verAlumnos.setText("Ver alumnos");
        verAlumnos.setMaximumSize(new java.awt.Dimension(150, 30));
        verAlumnos.setMinimumSize(new java.awt.Dimension(150, 30));
        verAlumnos.setPreferredSize(new java.awt.Dimension(150, 30));
        verAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verAlumnosActionPerformed(evt);
            }
        });
        profesor.add(verAlumnos, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 130, -1, -1));

        panelAltaMateria.setEnabled(false);
        panelAltaMateria.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Nombre de la materia:");
        jLabel4.setPreferredSize(new java.awt.Dimension(166, 28));
        panelAltaMateria.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        listaMaterias.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        listaMaterias.setMaximumSize(new java.awt.Dimension(200, 28));
        listaMaterias.setMinimumSize(new java.awt.Dimension(200, 28));
        listaMaterias.setPreferredSize(new java.awt.Dimension(200, 28));
        listaMaterias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaMateriasActionPerformed(evt);
            }
        });
        panelAltaMateria.add(listaMaterias, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, -1, -1));

        nombreMateria.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        nombreMateria.setPreferredSize(new java.awt.Dimension(64, 28));
        nombreMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreMateriaActionPerformed(evt);
            }
        });
        panelAltaMateria.add(nombreMateria, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, 200, -1));

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel5.setText("Nombre de la correlativa 1:");
        jLabel5.setPreferredSize(new java.awt.Dimension(204, 28));
        panelAltaMateria.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        listaCorrelativas1.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        listaCorrelativas1.setMaximumSize(new java.awt.Dimension(200, 28));
        listaCorrelativas1.setMinimumSize(new java.awt.Dimension(200, 28));
        listaCorrelativas1.setPreferredSize(new java.awt.Dimension(200, 28));
        panelAltaMateria.add(listaCorrelativas1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, -1, -1));

        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel6.setText("Nombre de la correlativa 2:");
        jLabel6.setPreferredSize(new java.awt.Dimension(204, 28));
        panelAltaMateria.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        listaCorrelativas2.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        listaCorrelativas2.setMaximumSize(new java.awt.Dimension(200, 28));
        listaCorrelativas2.setMinimumSize(new java.awt.Dimension(200, 28));
        listaCorrelativas2.setPreferredSize(new java.awt.Dimension(200, 28));
        panelAltaMateria.add(listaCorrelativas2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, -1, -1));

        jLabel7.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel7.setText("Nombre de la correlativa 3:");
        jLabel7.setPreferredSize(new java.awt.Dimension(204, 28));
        panelAltaMateria.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        listaCorrelativas3.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        listaCorrelativas3.setMaximumSize(new java.awt.Dimension(200, 28));
        listaCorrelativas3.setMinimumSize(new java.awt.Dimension(200, 28));
        listaCorrelativas3.setPreferredSize(new java.awt.Dimension(200, 28));
        panelAltaMateria.add(listaCorrelativas3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, -1, -1));

        jLabel8.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel8.setText("Nombre de la correlativa 4:");
        jLabel8.setPreferredSize(new java.awt.Dimension(204, 28));
        panelAltaMateria.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        listaCorrelativas4.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        listaCorrelativas4.setMaximumSize(new java.awt.Dimension(200, 28));
        listaCorrelativas4.setMinimumSize(new java.awt.Dimension(200, 28));
        listaCorrelativas4.setPreferredSize(new java.awt.Dimension(200, 28));
        panelAltaMateria.add(listaCorrelativas4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, -1, -1));

        jLabel9.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel9.setText("Nombre de la correlativa 5:");
        jLabel9.setPreferredSize(new java.awt.Dimension(204, 28));
        panelAltaMateria.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        listaCorrelativas5.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        listaCorrelativas5.setMaximumSize(new java.awt.Dimension(200, 28));
        listaCorrelativas5.setMinimumSize(new java.awt.Dimension(200, 28));
        listaCorrelativas5.setPreferredSize(new java.awt.Dimension(200, 28));
        panelAltaMateria.add(listaCorrelativas5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 230, -1, -1));
        panelAltaMateria.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        saveMateria.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        saveMateria.setText("Guardar Materia");
        saveMateria.setMaximumSize(new java.awt.Dimension(160, 23));
        saveMateria.setMinimumSize(new java.awt.Dimension(160, 23));
        saveMateria.setPreferredSize(new java.awt.Dimension(160, 23));
        saveMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveMateriaActionPerformed(evt);
            }
        });
        panelAltaMateria.add(saveMateria, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, -1, -1));

        limpiarCampos.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        limpiarCampos.setText("Borrar Campos");
        limpiarCampos.setMaximumSize(new java.awt.Dimension(160, 23));
        limpiarCampos.setMinimumSize(new java.awt.Dimension(160, 23));
        limpiarCampos.setPreferredSize(new java.awt.Dimension(160, 23));
        limpiarCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarCamposActionPerformed(evt);
            }
        });
        panelAltaMateria.add(limpiarCampos, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 280, -1, -1));

        nuevaMateria.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        nuevaMateria.setText("Nueva Materia");
        nuevaMateria.setMaximumSize(new java.awt.Dimension(150, 28));
        nuevaMateria.setMinimumSize(new java.awt.Dimension(150, 28));
        nuevaMateria.setPreferredSize(new java.awt.Dimension(150, 28));
        nuevaMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevaMateriaActionPerformed(evt);
            }
        });
        panelAltaMateria.add(nuevaMateria, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 30, 150, -1));

        volverLista.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        volverLista.setText("Volver a la lista");
        volverLista.setPreferredSize(new java.awt.Dimension(140, 28));
        volverLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverListaActionPerformed(evt);
            }
        });
        panelAltaMateria.add(volverLista, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 30, 150, -1));

        profesor.add(panelAltaMateria, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 600, 600));

        panelAltaAlumno.setEnabled(false);
        panelAltaAlumno.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel10.setText("Nombre del alumno:");
        jLabel10.setPreferredSize(new java.awt.Dimension(166, 28));
        panelAltaAlumno.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 160, -1));
        panelAltaAlumno.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        saveAlumno.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        saveAlumno.setText("Guardar alumno");
        saveAlumno.setPreferredSize(new java.awt.Dimension(150, 23));
        saveAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveAlumnoActionPerformed(evt);
            }
        });
        panelAltaAlumno.add(saveAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 360, -1, -1));

        limpiarCampos1.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        limpiarCampos1.setText("Borrar Campos");
        limpiarCampos1.setPreferredSize(new java.awt.Dimension(150, 23));
        limpiarCampos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarCampos1ActionPerformed(evt);
            }
        });
        panelAltaAlumno.add(limpiarCampos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 360, -1, -1));

        CargarNombreAlumno.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        CargarNombreAlumno.setPreferredSize(new java.awt.Dimension(64, 28));
        CargarNombreAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CargarNombreAlumnoActionPerformed(evt);
            }
        });
        panelAltaAlumno.add(CargarNombreAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, 200, -1));

        jScrollPane4.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane4.setMaximumSize(new java.awt.Dimension(580, 402));
        jScrollPane4.setMinimumSize(new java.awt.Dimension(580, 402));
        jScrollPane4.setPreferredSize(new java.awt.Dimension(580, 402));

        tablaMateriasAprobadas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Materia Aprobadas", "Seleccionar"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaMateriasAprobadas.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tablaMateriasAprobadas.setShowHorizontalLines(true);
        tablaMateriasAprobadas.setShowVerticalLines(true);
        jScrollPane4.setViewportView(tablaMateriasAprobadas);

        panelAltaAlumno.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 580, 260));

        profesor.add(panelAltaAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 600, 600));

        panelVerMaterias.setEnabled(false);
        panelVerMaterias.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel12.setText("Nombre de la materia:");
        jLabel12.setPreferredSize(new java.awt.Dimension(166, 28));
        panelVerMaterias.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 170, -1));
        panelVerMaterias.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        nombreMateriaAConsultar.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        nombreMateriaAConsultar.setPreferredSize(new java.awt.Dimension(64, 28));
        panelVerMaterias.add(nombreMateriaAConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 170, -1));

        ConsultarTodasLasMaterias.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        ConsultarTodasLasMaterias.setText("Consultar Todas");
        ConsultarTodasLasMaterias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultarTodasLasMateriasActionPerformed(evt);
            }
        });
        panelVerMaterias.add(ConsultarTodasLasMaterias, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, -1, -1));

        consultarMateriaPuntual.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        consultarMateriaPuntual.setText("Consultar Materia");
        consultarMateriaPuntual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarMateriaPuntualActionPerformed(evt);
            }
        });
        panelVerMaterias.add(consultarMateriaPuntual, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 170, -1));

        jScrollPane1.setMaximumSize(new java.awt.Dimension(580, 402));
        jScrollPane1.setMinimumSize(new java.awt.Dimension(580, 402));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(580, 402));

        tablaMaterias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Materia", "Correlativas"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaMaterias.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tablaMaterias.setShowHorizontalLines(true);
        tablaMaterias.setShowVerticalLines(true);
        jScrollPane1.setViewportView(tablaMaterias);

        panelVerMaterias.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 580, -1));

        profesor.add(panelVerMaterias, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 600, 600));

        panelVerAlumnos.setEnabled(false);
        panelVerAlumnos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panelVerAlumnos.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane2.setMaximumSize(new java.awt.Dimension(580, 402));
        jScrollPane2.setMinimumSize(new java.awt.Dimension(580, 402));
        jScrollPane2.setPreferredSize(new java.awt.Dimension(580, 402));

        tablaAlumnos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Legajo", "Materia", "Correlativas"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaAlumnos.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tablaAlumnos.setShowHorizontalLines(true);
        tablaAlumnos.setShowVerticalLines(true);
        jScrollPane2.setViewportView(tablaAlumnos);

        panelVerAlumnos.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 580, -1));

        jLabel13.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel13.setText("Legajo del Alumno:");
        jLabel13.setPreferredSize(new java.awt.Dimension(166, 28));
        panelVerAlumnos.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 150, -1));

        consultarAlumnoPuntual.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        consultarAlumnoPuntual.setText("Consultar Alumno");
        consultarAlumnoPuntual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarAlumnoPuntualActionPerformed(evt);
            }
        });
        panelVerAlumnos.add(consultarAlumnoPuntual, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 170, -1));

        ConsultarTodosLosAlumnos.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        ConsultarTodosLosAlumnos.setText("Consultar Todos");
        ConsultarTodosLosAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultarTodosLosAlumnosActionPerformed(evt);
            }
        });
        panelVerAlumnos.add(ConsultarTodosLosAlumnos, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, -1, -1));

        legajoAlumnoAConsultar.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        legajoAlumnoAConsultar.setToolTipText("");
        legajoAlumnoAConsultar.setMaximumSize(new java.awt.Dimension(170, 28));
        legajoAlumnoAConsultar.setMinimumSize(new java.awt.Dimension(170, 28));
        legajoAlumnoAConsultar.setPreferredSize(new java.awt.Dimension(170, 28));
        panelVerAlumnos.add(legajoAlumnoAConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, -1, -1));

        profesor.add(panelVerAlumnos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 600, 600));

        principal.add(profesor, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        login.setAlignmentX(0.0F);
        login.setAlignmentY(0.0F);
        login.setMaximumSize(new java.awt.Dimension(600, 800));
        login.setMinimumSize(new java.awt.Dimension(600, 800));
        login.setOpaque(false);
        login.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon.png"))); // NOI18N
        jLabel1.setFocusable(false);
        login.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 61, -1, -1));

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel2.setText("Usuario:");
        login.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 406, -1, -1));

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel3.setText("Password:");
        login.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 439, -1, -1));

        user.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userActionPerformed(evt);
            }
        });
        login.add(user, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 403, 200, -1));

        password.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        login.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 436, 200, -1));

        makeLogin.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        makeLogin.setText("Login");
        makeLogin.setToolTipText("");
        makeLogin.setAlignmentY(160.0F);
        makeLogin.setBorder(null);
        makeLogin.setBorderPainted(false);
        makeLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        makeLogin.setMaximumSize(new java.awt.Dimension(80, 30));
        makeLogin.setMinimumSize(new java.awt.Dimension(80, 30));
        makeLogin.setPreferredSize(new java.awt.Dimension(80, 30));
        makeLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                makeLoginActionPerformed(evt);
            }
        });
        login.add(makeLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 480, -1, -1));

        error1.setBackground(new java.awt.Color(0, 0, 0));
        error1.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        error1.setForeground(new java.awt.Color(255, 0, 0));
        error1.setText("Usuario invalido, recorda que,");
        error1.setPreferredSize(new java.awt.Dimension(227, 19));
        login.add(error1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 580, -1, -1));

        error2.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        error2.setForeground(new java.awt.Color(255, 0, 0));
        error2.setText("si sos profesor tenes que usar: usuario profe password profe");
        error2.setPreferredSize(new java.awt.Dimension(225, 19));
        login.add(error2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 610, 470, -1));

        error3.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        error3.setForeground(new java.awt.Color(255, 0, 0));
        error3.setText("y");
        error3.setPreferredSize(new java.awt.Dimension(238, 19));
        login.add(error3, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 631, 10, -1));

        error4.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        error4.setForeground(new java.awt.Color(255, 0, 0));
        error4.setText("si sos alumno tenes que usar: usuario numero de legajo password alumno");
        error4.setPreferredSize(new java.awt.Dimension(242, 19));
        login.add(error4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 660, 570, -1));

        principal.add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 800));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(principal, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(principal, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userActionPerformed

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_closeActionPerformed

    private void makeLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_makeLoginActionPerformed
        LogicaComun.ventana = this;
        try {
            LogicaComun.login();
        } catch (SQLException ex) {
            Logger.getLogger(Ventana.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_makeLoginActionPerformed

    private void altaMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_altaMateriaActionPerformed
        if (!ManejoDeDatos.verificarTabla("materias")) {
            String[] columnasACrear = new String[]{"materia TEXT","correlativas TEXT"};
            ManejoDeDatos.crearTabla("materias", columnasACrear);
        }
        panelVerMaterias.setVisible(false);
        panelVerAlumnos.setVisible(false);
        panelAltaAlumno.setVisible(false);
        nombreMateria.setVisible(false);
        volverLista.setVisible(false);
        this.refrescarMaterias();
        panelAltaMateria.setVisible(true);
    }//GEN-LAST:event_altaMateriaActionPerformed

    private void altaAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_altaAlumnoActionPerformed
        // TODO add your handling code here:
        tablaMateriasAprobadas.getColumnModel().getColumn(0).setPreferredWidth(principal.getWidth()-200);
        if (!ManejoDeDatos.verificarTabla("alumnos")) {
            String[] columnasACrear = new String[]{"legajo INT","nombre TEXT","aprobadas TEXT"};
            ManejoDeDatos.crearTabla("alumnos", columnasACrear);
        }
        if (ManejoDeDatos.verificarTabla("materias")) {
            try {
                Integrador.materias = new ArrayList<>(ManejoDeDatos.obtenerMaterias().values());
                this.refrescarTabla();
                panelVerMaterias.setVisible(false);
                panelVerAlumnos.setVisible(false);
                panelAltaMateria.setVisible(false);
                panelAltaAlumno.setVisible(true);
            } catch (SQLException ex) {
                Logger.getLogger(Ventana.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else{
            String mensaje = "No podes cargar alumnos ya que no hay materias cargadas.";
            String mensaje2 = "por favor, cargue algunas y vuelva a intentar.";
            llamarModal(mensaje, mensaje2);
        }
    }//GEN-LAST:event_altaAlumnoActionPerformed

    private void verMateriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verMateriasActionPerformed
        panelVerAlumnos.setVisible(false);
        panelAltaAlumno.setVisible(false);
        panelAltaMateria.setVisible(false);
        panelVerMaterias.setVisible(true);
    }//GEN-LAST:event_verMateriasActionPerformed

    private void verAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verAlumnosActionPerformed
        // TODO add your handling code here:
        if (!ManejoDeDatos.verificarTabla("alumnos")) {
            String[] columnasACrear = new String[]{"legajo INT","nombre TEXT","aprobadas TEXT"};
            ManejoDeDatos.crearTabla("alumnos", columnasACrear);
        }
        panelVerMaterias.setVisible(false);
        panelAltaAlumno.setVisible(false);
        panelAltaMateria.setVisible(false);
        panelVerAlumnos.setVisible(true);
    }//GEN-LAST:event_verAlumnosActionPerformed

    private void nuevaMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevaMateriaActionPerformed
        nombreMateria.setText("");
        listaMaterias.setSelectedIndex(-1);
        nuevaMateria.setVisible(false);
        listaMaterias.setVisible(false);
        nombreMateria.setVisible(true);
        volverLista.setVisible(true);
    }//GEN-LAST:event_nuevaMateriaActionPerformed

    private void volverListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverListaActionPerformed
        nombreMateria.setText("");
        listaMaterias.setSelectedIndex(-1);
        nombreMateria.setVisible(false);
        volverLista.setVisible(false);
        nuevaMateria.setVisible(true);
        listaMaterias.setVisible(true);
    }//GEN-LAST:event_volverListaActionPerformed

    private void saveAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveAlumnoActionPerformed
        // TODO add your handling code here:
        if(this.validarCamposCargaAlumno()){
            try {
                LogicaComun.enviarAltaAlumno();
            } catch (SQLException ex) {
                Logger.getLogger(Ventana.class.getName()).log(Level.SEVERE, null, ex);
            }
            this.limpiarAltaMaterias();
        }
    }//GEN-LAST:event_saveAlumnoActionPerformed

    private void limpiarCampos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarCampos1ActionPerformed
            this.borrarCamposAlumno();
    }//GEN-LAST:event_limpiarCampos1ActionPerformed

    private void cerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarSesionActionPerformed
        LogicaComun.logout();
    }//GEN-LAST:event_cerrarSesionActionPerformed

    private void listaMateriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaMateriasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listaMateriasActionPerformed

    private void saveMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveMateriaActionPerformed
        if (ManejoDeDatos.verificarTabla("materias")) {
            
            try {
                Integrador.materias = new ArrayList<>(ManejoDeDatos.obtenerMaterias().values());
            } catch (SQLException ex) {
                Logger.getLogger(Ventana.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        try {
            LogicaComun.enviarAltaMateria();
            refrescarMaterias();
        } catch (SQLException ex) {
            Logger.getLogger(Ventana.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_saveMateriaActionPerformed

    private void limpiarCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarCamposActionPerformed
        this.limpiarAltaMaterias();
    }//GEN-LAST:event_limpiarCamposActionPerformed

    private void consultarMateriaPuntualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarMateriaPuntualActionPerformed
        if (ManejoDeDatos.verificarTabla("materias")) {
            try {
                LogicaComun.ConsultarMateria();
                nombreMateriaAConsultar.setText("");
            } catch (SQLException ex) {
                Logger.getLogger(Ventana.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_consultarMateriaPuntualActionPerformed

    private void consultarAlumnoPuntualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarAlumnoPuntualActionPerformed
        try {
            // TODO add your handling code here:
            LogicaComun.ConsultarAlumno();
        } catch (SQLException ex) {
            Logger.getLogger(Ventana.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_consultarAlumnoPuntualActionPerformed

    private void ConsultarTodasLasMateriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultarTodasLasMateriasActionPerformed
        if (ManejoDeDatos.verificarTabla("materias")) {
            try {
                LogicaComun.consultarTodasLasMaterias();
            } catch (SQLException ex) {
                Logger.getLogger(Ventana.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_ConsultarTodasLasMateriasActionPerformed

    private void ConsultarTodosLosAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultarTodosLosAlumnosActionPerformed
        try {
            // TODO add your handling code here:
            LogicaComun.consultarTodosLosAlumnos();
        } catch (SQLException ex) {
            Logger.getLogger(Ventana.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ConsultarTodosLosAlumnosActionPerformed

    private void inscripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inscripcionActionPerformed
        if (ManejoDeDatos.verificarTabla("materias")) {
            panelInscripcion.setVisible(true);
            
            try {
                Integrador.materias = new ArrayList<>(ManejoDeDatos.obtenerMaterias().values());
            } catch (SQLException ex) {
                Logger.getLogger(Ventana.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else{
            String mensaje = "No podes inscribirte porque aun no hay materias cargadas.";
            String mensaje2 = "por favor pidele a tu profe que cargue algunas.";
            llamarModal(mensaje, mensaje2);
        }
        tablaInscripcion.getColumnModel().getColumn(0).setPreferredWidth(principal.getWidth()-100);
    }//GEN-LAST:event_inscripcionActionPerformed

    private void ConsultarMateriasParaInscripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultarMateriasParaInscripcionActionPerformed
        try {
            // TODO add your handling code here:
            LogicaComun.ConsultarAlumnoParaInscribir();
            tablaInscripcion.getColumnModel().getColumn(0).setPreferredWidth(principal.getWidth()-100);
        } catch (SQLException ex) {
            Logger.getLogger(Ventana.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ConsultarMateriasParaInscripcionActionPerformed

    private void Inscribir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Inscribir1ActionPerformed
        // TODO add your handling code here:
        System.out.println("click");
        try {
            if(this.validarCamposInscripcionAlumno()){
                System.out.println("seValido");
                try {
                    LogicaComun.enviarInscripcionAlumno();
                } catch (SQLException ex) {
                    Logger.getLogger(Ventana.class.getName()).log(Level.SEVERE, null, ex);
                }
                this.limpiarAltaMaterias();
            }
        } catch (SQLException ex) {
            Logger.getLogger(Ventana.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Inscribir1ActionPerformed

    private void CargarNombreAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CargarNombreAlumnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CargarNombreAlumnoActionPerformed

    private void nombreMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreMateriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreMateriaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }
    
    public void loginError() {
        error1.setVisible(true);
        error2.setVisible(true);
        error3.setVisible(true);
        error4.setVisible(true);
    }
    
    public void cleanError() {
        error1.setVisible(false);
        error2.setVisible(false);
        error3.setVisible(false);
        error4.setVisible(false);
    }
    
    public void borrarCamposAlumno() {
        CargarNombreAlumno.setText("");
        for (int i = 0; i < tablaMateriasAprobadas.getRowCount(); i++) {
            tablaMateriasAprobadas.setValueAt(false, i, 1);
        }
    }
    
    public boolean validarCamposCargaAlumno() {
        boolean esNombreValido = !CargarNombreAlumno.getText().equals("");
        return esNombreValido;
    }
    
    public boolean validarCamposInscripcionAlumno() throws SQLException {
        int legajo = (int)legajoAlumnoAInscribir.getValue();
        ArrayList resultado = ManejoDeDatos.buscarLineaIntegerGeneral("alumnos", "legajo", legajo);
        boolean existeInscripcion = false;
        for (int i = 0; i < tablaMateriasAprobadas.getRowCount(); i++) {
            if ((Boolean)tablaMateriasAprobadas.getValueAt(i, 1)) { // Columna "Seleccionar"
                existeInscripcion = true;
            }
        }
        if (!resultado.isEmpty()) {
            return true;
        }
        boolean esNombreValido = !CargarNombreAlumno.getText().equals("");
        return esNombreValido && existeInscripcion;
    }
    
    public void limpiarAltaMaterias() {
        nombreMateria.setText("");
        listaMaterias.setSelectedIndex(-1);
        listaCorrelativas1.setSelectedIndex(-1);
        listaCorrelativas2.setSelectedIndex(-1);
        listaCorrelativas3.setSelectedIndex(-1);
        listaCorrelativas4.setSelectedIndex(-1);
        listaCorrelativas5.setSelectedIndex(-1);
    }
    
    public void refrescarMaterias(){
        try {
            JComboBox[] combos =  new JComboBox[]{listaMaterias, listaCorrelativas1, listaCorrelativas2, listaCorrelativas3, listaCorrelativas4, listaCorrelativas5};
            String[] response = ManejoDeDatos.consultarTabla("listadoMaterias", "materias");
            for(JComboBox comboBox : combos) {
                comboBox.setModel(new DefaultComboBoxModel<>(response));
            }
        } catch (SQLException ex) {
            Logger.getLogger(Ventana.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.limpiarAltaMaterias();
    }
    
    public void refrescarTabla(){
        try {
            String[] materias = ManejoDeDatos.consultarTabla("listadoMaterias", "materias");
            DefaultTableModel modelo = (DefaultTableModel) tablaMateriasAprobadas.getModel();
            List<String> lista = new ArrayList(Integrador.materias.size());
            modelo.setRowCount(0);
            int i = 0;
            for(Materia materia : Integrador.materias){
                lista.add(materia.getNombre());
                i++;
            }
            for (String materia : materias) {
                if (lista.contains(materia)) {
                    modelo.addRow(new Object[]{materia, false});
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(Ventana.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.limpiarAltaMaterias();
    }
    
    public void CargarTablaDeMateriasDadasDeAlta(){
        try {
            String[] materias = ManejoDeDatos.consultarTabla("listadoMaterias", "materias");
            DefaultTableModel modelo = (DefaultTableModel) tablaMateriasAprobadas.getModel();
            for (String materia : materias) {
                modelo.addRow(new Object[]{materia, false});
            }
        } catch (SQLException ex) {
            Logger.getLogger(Ventana.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.limpiarAltaMaterias();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CargarNombreAlumno;
    private javax.swing.JButton ConsultarMateriasParaInscripcion;
    private javax.swing.JButton ConsultarTodasLasMaterias;
    private javax.swing.JButton ConsultarTodosLosAlumnos;
    private javax.swing.JButton Inscribir1;
    private javax.swing.JButton altaAlumno;
    private javax.swing.JButton altaMateria;
    private javax.swing.JPanel alumno;
    private javax.swing.JButton cerrarSesion;
    private javax.swing.JButton close;
    private javax.swing.JButton consultarAlumnoPuntual;
    private javax.swing.JButton consultarMateriaPuntual;
    private javax.swing.JLabel error1;
    private javax.swing.JLabel error2;
    private javax.swing.JLabel error3;
    private javax.swing.JLabel error4;
    private javax.swing.JButton inscripcion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSpinner legajoAlumnoAConsultar;
    private javax.swing.JSpinner legajoAlumnoAInscribir;
    private javax.swing.JButton limpiarCampos;
    private javax.swing.JButton limpiarCampos1;
    private javax.swing.JComboBox<String> listaCorrelativas1;
    private javax.swing.JComboBox<String> listaCorrelativas2;
    private javax.swing.JComboBox<String> listaCorrelativas3;
    private javax.swing.JComboBox<String> listaCorrelativas4;
    private javax.swing.JComboBox<String> listaCorrelativas5;
    private javax.swing.JComboBox<String> listaMaterias;
    private javax.swing.JPanel login;
    private javax.swing.JButton makeLogin;
    private javax.swing.JTextField nombreMateria;
    private javax.swing.JTextField nombreMateriaAConsultar;
    private javax.swing.JButton nuevaMateria;
    private javax.swing.JPanel panelAltaAlumno;
    private javax.swing.JPanel panelAltaMateria;
    private javax.swing.JPanel panelInscripcion;
    private javax.swing.JPanel panelVerAlumnos;
    private javax.swing.JPanel panelVerMaterias;
    private javax.swing.JPasswordField password;
    private javax.swing.JPanel principal;
    private javax.swing.JPanel profesor;
    private javax.swing.JButton saveAlumno;
    private javax.swing.JButton saveMateria;
    private javax.swing.JTable tablaAlumnos;
    private javax.swing.JTable tablaInscripcion;
    private javax.swing.JTable tablaMaterias;
    private javax.swing.JTable tablaMateriasAprobadas;
    private javax.swing.JTextField user;
    private javax.swing.JButton verAlumnos;
    private javax.swing.JButton verMaterias;
    private javax.swing.JButton volverLista;
    // End of variables declaration//GEN-END:variables
}

class FondoPanel extends JPanel {
    private Image imagen;
    
    @Override
    public void paint(Graphics g){
        imagen = new javax.swing.ImageIcon(getClass().getResource("/bg.jpeg")).getImage();
        g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
        
        setOpaque(false);
        super.paint(g);
    }
}
